In [65]:
import pandas as pd
import numpy as np
import matplotlib as plt
import re
import json
from tornado import ioloop, httpclient

In [12]:
# Loading user-related data
users = pd.read_csv('data/ml-100k/u.user', sep='|', header=None, names=['id','age','gender','occupation','zip code'], encoding='cp1252')
n_u = users.shape[0]

# Loading genres of movies
genres = pd.read_csv('data/ml-100k/u.genre', sep='|', header=None, names=['name', 'id'], encoding='cp1252')
n_g = genres.shape[0]

# Loading item-related data
# Format : id | title | release date | | IMDb url | "genres"
# where "genres" is a vector of size n_g : genres[i]=1 if the movie belongs to genre i
movie_col = ['id', 'title','release date', 'useless', 'IMDb url']
movie_col = movie_col + genres['id'].tolist()
movies = pd.read_csv('data/ml-100k/u.item', sep='|', header=None, names=movie_col, encoding='cp1252')
movies = movies.fillna('unknown')
n_m = movies.shape[0]

# Loading ratings
rating_col = ['user_id', 'item_id','rating', 'timestamp']
ratings = pd.read_csv('data/ml-100k/u.data', sep='\t' ,header=None, names=rating_col, encoding='cp1252')
n_r = ratings.shape[0]

In [13]:
from imdb import IMDb
ia = IMDb()
from lxml import html
import requests
#
movies['synopsis'] = ''
movies['storyline'] = ''
movies['description']= ''
movies['text'] = ''

In [14]:
movies.head()

,id,title,release date,useless,IMDb url,0,1,2,3,4,...,13,14,15,16,17,18,synopsis,storyline,description,text
0,1,Toy Story (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,,,,
1,2,GoldenEye (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,1,0,0,,,,
2,3,Four Rooms (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,1,0,0,,,,
3,4,Get Shorty (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,,,,
4,5,Copycat (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,1,0,0,,,,

In [36]:
url = 'http://www.imdb.com/find?q={}&s=tt&exact=true&ref_=fn_tt_ex'.format('Toy Story (1995)')
page = requests.get(url)
tree = html.fromstring(page.content)
# Get the movie id 
idm = re.match('tt(\d+)',tree.xpath('//td[@class="result_text"]//a/@href')[0].split('/')[2]).group(1)
print (idm)
# # Toy%20Story%20%281995%29

0114709

In [45]:
ia.get_movie(idm)

In [33]:
s_result = ia.search_movie('Toy Story')

# Print the long imdb canonical title and movieID of the results.
for item in s_result:
   print item['long imdb canonical title'], item.movieID

Toy Story (1995) 0114709
Toy Story (1996) (VG) 0178952
Toy Story (1992) 0847116
Toy Story 3 (2010) 0435761
Toy Story 4 (2019) 1979376
Toy Story 2 (1999) 0120363
Toy Story That Time Forgot (2014) 3473654
Toy Story of Terror (2013) 2446040
Toy Story 2 (I) (1999) (VG) 0395789
Toy Story 3 (2010) (VG) 5157912
"Toy Stories" (2009) 1536735
Toy Story 2 (II) (1999) (VG) 6735010
Toy Story Toons: Small Fry (2011) 2033372
History Boys, The (2006) 0464049
It's Kind of a Funny Story (2010) 0804497
Story Behind 'Toy Story', The (2000) (V) 0220070
Toy Story Toons: Hawaiian Vacation (2011) 1850374
"Toy Story Treats" (1996) 1716710
"Toy Story 3 (2015) (TV Episode)  - Season 11 | Episode 7  - Jambareeqi Reviews" (2012) 5353380
"Toy Story (2013) (TV Episode)  - Season 3 | Episode 1  - The Exes" (2011) 2579110

In [78]:
from imdb import IMDb
ia = IMDb()
from lxml import html
import requests
#
movies['synopsis'] = ''
movies['storyline'] = ''
movies['description']= ''
movies['text'] = ''
# Looping over movies
for index, row in movies.iterrows():
    if index > 1:
        break
    if (row['IMDb url'] != 'unknown'):
        # Get the html content 
        try:
            url = 'http://www.imdb.com/find?q={}&s=tt&exact=true&ref_=fn_tt_ex'.format(row['title'])
            page = requests.get(url)
            tree = html.fromstring(page.content)
            # Get the movie id 
            idm = re.match('tt(\d+)',tree.xpath('//td[@class="result_text"]//a/@href')[0].split('/')[2]).group(1)

            #             page = requests.get(row['IMDb url'])
            #             tree = html.fromstring(page.content)
            # Get the movie id 
            #             idm = tree.xpath('/html/head/meta[6]')[0].get('content')[2:]
            print (idm)
            
            # Get the story line
            page = requests.get('http://www.imdb.com/title/tt{}/?ref_=fn_tt_tt_1'.format(idm))
            tree = html.fromstring(page.content)
            movies.loc[index, 'storyline'] = tree.xpath('//div[@id="titleStoryLine"]/div[1]/p')[0].text
            # Get the movie using the IMDB library based on the movie id
#             m = ia.get_movie(idm)
            # Get the descreption 
#             movies.loc[index, 'description'] = m.get('plot outline')
            # Get the synopsis
#             ia.update(m, 'synopsis')
#             if m.get('synopsis') is not None:
#                 movies.loc[index, 'synopsis'] = m.get('synopsis')
        except IndexError:
            print row['IMDb url']
#             pass
    # Create a text field to concatenate all existing summaries
    movies.loc[index, 'text'] = movies.loc[index, 'description'] + ' ' + movies.loc[index, 'storyline'] + ' '+ movies.loc[index, 'synopsis']

0114709
0113189

In [ ]:

from imdb import IMDb
ia = IMDb()
from lxml import html
import requests
#
movies['synopsis'] = ''
movies['storyline'] = ''
movies['description']= ''
movies['text'] = ''



def populate_storyline(page,index):
    tree = html.fromstring(page.content)
    movies.loc[index, 'storyline'] = tree.xpath('//div[@id="titleStoryLine"]/div[1]/p')[0].text
    movies.loc[index, 'text'] = movies.loc[index, 'description'] + ' ' + movies.loc[index, 'storyline'] + ' '+ movies.loc[index, 'synopsis']
    

def populate_idm(page,index):
    tree = html.fromstring(page.content)
    idm = re.match('tt(\d+)',tree.xpath('//td[@class="result_text"]//a/@href')[0].split('/')[2]).group(1)
    url = 'http://www.imdb.com/title/tt{}/?ref_=fn_tt_tt_1'.format(idm)
    cb_pop_story = lambda page: populate_storyline(page,index)
    http_client.fetch(url.strip(), cb_pop_story, method='GET')
    
    


# Looping over movies
for index, row in movies.iterrows():
    if index > 1:
        break
    if (row['IMDb url'] != 'unknown'):
        # Get the html content 
        try:
            url = 'http://www.imdb.com/find?q={}&s=tt&exact=true&ref_=fn_tt_ex'.format(row['title'])
            cb_pop_idm = lambda page: populate_idm(page,index)
            http_client.fetch(url.strip(), cb_pop_idm, method='GET')
        except IndexError:
            print row['IMDb url']
#             pass
    # Create a text field to concatenate all existing summaries
    
ioloop.IOLoop.instance().start()

In [79]:
movies.head()

,id,title,release date,useless,IMDb url,0,1,2,3,4,...,13,14,15,16,17,18,synopsis,storyline,description,text
0,1,Toy Story (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,,\nA little boy named Andy loves to be in his r...,,\nA little boy named Andy loves to be in his ...
1,2,GoldenEye (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,1,0,0,,\nWhen a deadly satellite weapon system falls ...,,\nWhen a deadly satellite weapon system falls...
2,3,Four Rooms (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,1,0,0,,,,
3,4,Get Shorty (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,,,,
4,5,Copycat (1995),01-Jan-1995,unknown,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,1,0,0,,,,

In [73]:
idm = 0114709
page = requests.get('http://www.imdb.com/title/tt{}/?ref_=fn_tt_tt_1'.format(idm))
tree = html.fromstring(page.content)
print tree.xpath('//div[@id="titleStoryLine"]/div[1]/p')[0].text

SyntaxError: invalid token (<ipython-input-73-02a1ccb2c972>, line 1)

In [ ]:
from nltk.tokenize import RegexpTokenizer
rt = RegexpTokenizer(r'\w+')
s = 'this is a; text-with tokens, and with punctuations.'


s.apply((lambda x: ' '.join(rt.tokenize(x))))